SOCIAL_AUTH_LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'

SOCIAL_AUTH_TWITTER_KEY = '4TAIm0nCMp47eWisjVvNuCIID'
SOCIAL_AUTH_TWITTER_SECRET = 'lwrRek2Sowigdy07gmk42p05pKHwqzr7WdRpFd0DwoM2VUWfYl'